// ======================================================
// DeKUT Nexus — Shared Product Catalogue
// Single source of truth for the homepage, catalogue page
// and product detail page. Swap PRODUCTS for a fetch() call
// to the FastAPI backend later without touching page logic.
// ======================================================

const PRODUCTS = [
  {
    id: 1,
    name: "Rabbit Meat",
    category: "new",
    section: "What's New",
    price: 800.0,
    priceDisplay: "KSh 800 /kg",
    unit: "kg",
    rating: 4.8,
    image: "images/products/rabbitmeat.png",
    description: "A recently added product from DeKUT Enterprise, freshly stocked and ready to order.",
    location: "Enterprise Shop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 2,
    name: "Macadamia Seedlings",
    category: "new",
    section: "What's New",
    price: 250.0,
    priceDisplay: "KSh 250",
    unit: "",
    rating: 4.8,
    image: "images/products/macadamia seedlings.png",
    description: "A recently added product from DeKUT Enterprise, freshly stocked and ready to order.",
    location: "Enterprise Shop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 3,
    name: "DeKUT Shirts 2026 Edition",
    category: "new",
    section: "What's New",
    price: 1000.0,
    priceDisplay: "KSh 1000",
    unit: "",
    rating: 5.0,
    image: "images/products/shirts.png",
    description: "A recently added product from DeKUT Enterprise, freshly stocked and ready to order.",
    location: "Enterprise Shop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 4,
    name: "Eco-Friendly Hand Wash",
    category: "new",
    section: "What's New",
    price: 200.0,
    priceDisplay: "KSh 200",
    unit: "",
    rating: 4.8,
    image: "images/products/handwash.png",
    description: "A recently added product from DeKUT Enterprise, freshly stocked and ready to order.",
    location: "Enterprise Shop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 5,
    name: "Vanilla Chia",
    category: "new",
    section: "What's New",
    price: 100.0,
    priceDisplay: "KSh 100",
    unit: "",
    rating: 4.9,
    image: "images/products/vanilla chia.png",
    description: "A recently added product from DeKUT Enterprise, freshly stocked and ready to order.",
    location: "Enterprise Shop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 6,
    name: "Fresh Tomatoes",
    category: "featured",
    section: "Featured This Week",
    price: 30.0,
    priceDisplay: "KSh 30 / Kg",
    unit: "Kg",
    rating: 5.0,
    image: "images/products/tomatoes.png",
    description: "A fresh pick straight from DeKUT Farms, harvested for quality and taste.",
    location: "DeKUT Farms",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 7,
    name: "Green Cabbages",
    category: "featured",
    section: "Featured This Week",
    price: 30.0,
    priceDisplay: "KSh 30 Each",
    unit: "Each",
    rating: 4.9,
    image: "images/products/cabbages.png",
    description: "A fresh pick straight from DeKUT Farms, harvested for quality and taste.",
    location: "DeKUT Farms",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 8,
    name: "Fresh Avocados",
    category: "featured",
    section: "Featured This Week",
    price: 20.0,
    priceDisplay: "KSh 20 Each",
    unit: "Each",
    rating: 4.8,
    image: "images/products/avocados.png",
    description: "A fresh pick straight from DeKUT Farms, harvested for quality and taste.",
    location: "DeKUT Farms",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 9,
    name: "Sweet Bananas",
    category: "featured",
    section: "Featured This Week",
    price: 15.0,
    priceDisplay: "KSh 15 Each",
    unit: "Each",
    rating: 4.9,
    image: "images/products/bananas.png",
    description: "A fresh pick straight from DeKUT Farms, harvested for quality and taste.",
    location: "DeKUT Farms",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 10,
    name: "Back To School Bundle",
    category: "bundles",
    section: "Bundle Offers",
    price: 350.0,
    priceDisplay: "KSh 350",
    unit: "",
    rating: null,
    image: "images/products/back2skool.png",
    description: "A specially curated bundle offering great value when purchased together.",
    location: "Enterprise Shop",
    available: true,
    ctaText: "View Bundle",
  },
  {
    id: 11,
    name: "Healthy Family Basket",
    category: "bundles",
    section: "Bundle Offers",
    price: 1150.0,
    priceDisplay: "KSh 1150",
    unit: "",
    rating: null,
    image: "images/products/healthy family.png",
    description: "A specially curated bundle offering great value when purchased together.",
    location: "Enterprise Shop",
    available: true,
    ctaText: "View Bundle",
  },
  {
    id: 12,
    name: "Coffee Lovers Pack",
    category: "bundles",
    section: "Bundle Offers",
    price: 999.0,
    priceDisplay: "KSh 999",
    unit: "",
    rating: null,
    image: "images/products/branded coffee mugs .png",
    description: "A specially curated bundle offering great value when purchased together.",
    location: "Enterprise Shop",
    available: true,
    ctaText: "View Bundle",
  },
  {
    id: 13,
    name: "DeKUT Gift Pack",
    category: "bundles",
    section: "Bundle Offers",
    price: 290.0,
    priceDisplay: "KSh 290",
    unit: "",
    rating: null,
    image: "images/products/mega pack.png",
    description: "A specially curated bundle offering great value when purchased together.",
    location: "Enterprise Shop",
    available: true,
    ctaText: "View Bundle",
  },
  {
    id: 14,
    name: "Fresh Tomatoes",
    category: "agriculture",
    section: "Agricultural Products",
    price: 30.0,
    priceDisplay: "KSh 30 / Kg",
    unit: "Kg",
    rating: 4.9,
    image: "images/products/tomatoes.png",
    description: "Fresh farm produce grown and harvested at DeKUT Farms.",
    location: "DeKUT Farms",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 15,
    name: "Green Cabbages",
    category: "agriculture",
    section: "Agricultural Products",
    price: 30.0,
    priceDisplay: "KSh 30 Each",
    unit: "Each",
    rating: 4.8,
    image: "images/products/cabbages.png",
    description: "Fresh farm produce grown and harvested at DeKUT Farms.",
    location: "DeKUT Farms",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 16,
    name: "Fresh Spinach",
    category: "agriculture",
    section: "Agricultural Products",
    price: 25.0,
    priceDisplay: "KSh 25 Per Bunch",
    unit: "Per Bunch",
    rating: 4.9,
    image: "images/products/mafakee.png",
    description: "Fresh farm produce grown and harvested at DeKUT Farms.",
    location: "DeKUT Farms",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 17,
    name: "Kales (Sukuma Wiki)",
    category: "agriculture",
    section: "Agricultural Products",
    price: 20.0,
    priceDisplay: "KSh 20 Per Bunch",
    unit: "Per Bunch",
    rating: 4.8,
    image: "images/products/kales.png",
    description: "Fresh farm produce grown and harvested at DeKUT Farms.",
    location: "DeKUT Farms",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 18,
    name: "Fresh Onions",
    category: "agriculture",
    section: "Agricultural Products",
    price: 40.0,
    priceDisplay: "KSh 40 / Kg",
    unit: "Kg",
    rating: 4.7,
    image: "images/onions.png",
    description: "Fresh farm produce grown and harvested at DeKUT Farms.",
    location: "DeKUT Farms",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 19,
    name: "Ground Coffee",
    category: "coffee",
    section: "Coffee Products",
    price: 450.0,
    priceDisplay: "KSh 450",
    unit: "",
    rating: 5.0,
    image: "images/products/dekut coffee.png",
    description: "Premium coffee proudly grown, roasted and processed at DeKUT.",
    location: "Coffee Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 20,
    name: "Coffee Beans",
    category: "coffee",
    section: "Coffee Products",
    price: 500.0,
    priceDisplay: "KSh 500",
    unit: "",
    rating: 4.9,
    image: "images/products/coffee mbosho.png",
    description: "Premium coffee proudly grown, roasted and processed at DeKUT.",
    location: "Coffee Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 21,
    name: "Arabica Coffee",
    category: "coffee",
    section: "Coffee Products",
    price: 450.0,
    priceDisplay: "KSh 450",
    unit: "",
    rating: 4.8,
    image: "images/products/Arabica.png",
    description: "Premium coffee proudly grown, roasted and processed at DeKUT.",
    location: "Coffee Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 22,
    name: "Vanilla Yoghurt",
    category: "coffee",
    section: "Coffee Products",
    price: 470.0,
    priceDisplay: "KSh 470",
    unit: "",
    rating: 4.9,
    image: "images/products/vanilla chia.png",
    description: "Premium coffee proudly grown, roasted and processed at DeKUT.",
    location: "Coffee Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 23,
    name: "Espresso Coffee",
    category: "coffee",
    section: "Coffee Products",
    price: 520.0,
    priceDisplay: "KSh 520",
    unit: "",
    rating: 5.0,
    image: "images/products/Expresso.png",
    description: "Premium coffee proudly grown, roasted and processed at DeKUT.",
    location: "Coffee Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 24,
    name: "Fresh Milk",
    category: "dairy",
    section: "Dairy Products",
    price: 70.0,
    priceDisplay: "KSh 70 / Litre",
    unit: "Litre",
    rating: 5.0,
    image: "images/products/iria.png",
    description: "Fresh dairy product made daily at the DeKUT Dairy Unit.",
    location: "Dairy Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 25,
    name: "Vanilla Chia 500ml Yoghurt",
    category: "dairy",
    section: "Dairy Products",
    price: 120.0,
    priceDisplay: "KSh 120",
    unit: "",
    rating: 4.8,
    image: "images/products/vanilla chia.png",
    description: "Fresh dairy product made daily at the DeKUT Dairy Unit.",
    location: "Dairy Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 26,
    name: "Coffee 500ml Yoghurt",
    category: "dairy",
    section: "Dairy Products",
    price: 100.0,
    priceDisplay: "KSh 100",
    unit: "",
    rating: 4.9,
    image: "images/placeholder.svg",
    description: "Fresh dairy product made daily at the DeKUT Dairy Unit.",
    location: "Dairy Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 27,
    name: "Vanilla 250ml Yoghurt",
    category: "dairy",
    section: "Dairy Products",
    price: 55.0,
    priceDisplay: "KSh 55",
    unit: "",
    rating: 4.9,
    image: "images/placeholder.svg",
    description: "Fresh dairy product made daily at the DeKUT Dairy Unit.",
    location: "Dairy Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 28,
    name: "Strawberry 500ml Yoghurt",
    category: "dairy",
    section: "Dairy Products",
    price: 100.0,
    priceDisplay: "KSh 100",
    unit: "",
    rating: 5.0,
    image: "images/placeholder.svg",
    description: "Fresh dairy product made daily at the DeKUT Dairy Unit.",
    location: "Dairy Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 29,
    name: "Strawberry 1l Yoghurt",
    category: "dairy",
    section: "Dairy Products",
    price: 180.0,
    priceDisplay: "KSh 180",
    unit: "",
    rating: 5.0,
    image: "images/placeholder.svg",
    description: "Fresh dairy product made daily at the DeKUT Dairy Unit.",
    location: "Dairy Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 30,
    name: "Strawberry 250ml Yoghurt",
    category: "dairy",
    section: "Dairy Products",
    price: 55.0,
    priceDisplay: "KSh 55",
    unit: "",
    rating: 5.0,
    image: "images/placeholder.svg",
    description: "Fresh dairy product made daily at the DeKUT Dairy Unit.",
    location: "Dairy Unit",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 31,
    name: "Macadamia Seedlings",
    category: "seedlings",
    section: "Tree Seedlings",
    price: 250.0,
    priceDisplay: "KSh 250",
    unit: "",
    rating: 5.0,
    image: "images/products/macadamia seedlings.png",
    description: "High-quality seedlings nursed at the DeKUT Agriculture Department, ready for planting.",
    location: "Agriculture Department",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 32,
    name: "Coffee Seedlings",
    category: "seedlings",
    section: "Tree Seedlings",
    price: 120.0,
    priceDisplay: "KSh 120",
    unit: "",
    rating: 4.8,
    image: "images/products/coffe seedlings.png",
    description: "High-quality seedlings nursed at the DeKUT Agriculture Department, ready for planting.",
    location: "Agriculture Department",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 33,
    name: "Avocado Seedlings",
    category: "seedlings",
    section: "Tree Seedlings",
    price: 150.0,
    priceDisplay: "KSh 150",
    unit: "",
    rating: 4.9,
    image: "images/placeholder.svg",
    description: "High-quality seedlings nursed at the DeKUT Agriculture Department, ready for planting.",
    location: "Agriculture Department",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 34,
    name: "Grevillea Seedlings",
    category: "seedlings",
    section: "Tree Seedlings",
    price: 80.0,
    priceDisplay: "KSh 80",
    unit: "",
    rating: 4.7,
    image: "images/placeholder.svg",
    description: "High-quality seedlings nursed at the DeKUT Agriculture Department, ready for planting.",
    location: "Agriculture Department",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 35,
    name: "Indigenous Tree Seedlings",
    category: "seedlings",
    section: "Tree Seedlings",
    price: 100.0,
    priceDisplay: "KSh 100",
    unit: "",
    rating: 5.0,
    image: "images/placeholder.svg",
    description: "High-quality seedlings nursed at the DeKUT Agriculture Department, ready for planting.",
    location: "Agriculture Department",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 36,
    name: "DeKUT Hoodie",
    category: "merchandise",
    section: "DeKUT Merchandise",
    price: 1000.0,
    priceDisplay: "KSh 1,000",
    unit: "",
    rating: 5.0,
    image: "images/placeholder.svg",
    description: "Official DeKUT branded merchandise, a great way to show your DeKUT pride.",
    location: "University Bookshop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 37,
    name: "Official Polo T-Shirt",
    category: "merchandise",
    section: "DeKUT Merchandise",
    price: 700.0,
    priceDisplay: "KSh 700",
    unit: "",
    rating: 4.8,
    image: "images/placeholder.svg",
    description: "Official DeKUT branded merchandise, a great way to show your DeKUT pride.",
    location: "University Bookshop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 38,
    name: "DeKUT Cap",
    category: "merchandise",
    section: "DeKUT Merchandise",
    price: 500.0,
    priceDisplay: "KSh 500",
    unit: "",
    rating: 4.8,
    image: "images/placeholder.svg",
    description: "Official DeKUT branded merchandise, a great way to show your DeKUT pride.",
    location: "University Bookshop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 39,
    name: "Branded Coffee Mug",
    category: "merchandise",
    section: "DeKUT Merchandise",
    price: 450.0,
    priceDisplay: "KSh 450",
    unit: "",
    rating: 4.9,
    image: "images/products/branded coffee mugs .png",
    description: "Official DeKUT branded merchandise, a great way to show your DeKUT pride.",
    location: "University Bookshop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 40,
    name: "DeKUT Notebook",
    category: "merchandise",
    section: "DeKUT Merchandise",
    price: 400.0,
    priceDisplay: "KSh 400",
    unit: "",
    rating: 4.8,
    image: "images/placeholder.svg",
    description: "Official DeKUT branded merchandise, a great way to show your DeKUT pride.",
    location: "University Bookshop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 41,
    name: "Branded Overalls",
    category: "merchandise",
    section: "DeKUT Merchandise",
    price: 1000.0,
    priceDisplay: "KSh 1,000",
    unit: "",
    rating: 5.0,
    image: "images/placeholder.svg",
    description: "Official DeKUT branded merchandise, a great way to show your DeKUT pride.",
    location: "University Bookshop",
    available: true,
    ctaText: "View Product",
  },
  {
    id: 42,
    name: "Student Tour",
    category: "wildlife",
    section: "Wildlife Tours",
    price: 200.0,
    priceDisplay: "KSh 200 per person",
    unit: "per person",
    rating: 4.9,
    image: "images/wildlife/zebras.png",
    description: "A guided experience at the DeKUT Wildlife Conservancy.",
    location: "Wildlife Conservancy",
    available: true,
    ctaText: "Book Now",
  },
  {
    id: 43,
    name: "Conference Hall",
    category: "conference",
    section: "Conference & Accommodation",
    price: 15000.0,
    priceDisplay: "From KSh 15,000",
    unit: "",
    rating: null,
    image: "images/placeholder.svg",
    description: "Professional conference and accommodation services at DeKUT.",
    location: "Conference Centre",
    available: true,
    ctaText: "Book Now",
  },
  {
    id: 44,
    name: "Satima Dome",
    category: "conference",
    section: "Conference & Accommodation",
    price: null,
    priceDisplay: "Contact For Pricing",
    unit: "",
    rating: null,
    image: "images/placeholder.svg",
    description: "Professional conference and accommodation services at DeKUT.",
    location: "Conference Centre",
    available: true,
    ctaText: "Book Now",
  },
  {
    id: 45,
    name: "Guest Rooms",
    category: "conference",
    section: "Conference & Accommodation",
    price: 4500.0,
    priceDisplay: "From KSh 4,500 / Night",
    unit: "Night",
    rating: null,
    image: "images/placeholder.svg",
    description: "Professional conference and accommodation services at DeKUT.",
    location: "Conference Centre",
    available: true,
    ctaText: "Book Now",
  },
  {
    id: 46,
    name: "Seminar Room",
    category: "conference",
    section: "Conference & Accommodation",
    price: 8000.0,
    priceDisplay: "From KSh 8,000",
    unit: "",
    rating: null,
    image: "images/placeholder.svg",
    description: "Professional conference and accommodation services at DeKUT.",
    location: "Conference Centre",
    available: true,
    ctaText: "Book Now",
  },
  {
    id: 47,
    name: "Conference Catering",
    category: "conference",
    section: "Conference & Accommodation",
    price: null,
    priceDisplay: "Custom Packages",
    unit: "",
    rating: null,
    image: "images/wildlife/restaurant.png",
    description: "Professional conference and accommodation services at DeKUT.",
    location: "Conference Centre",
    available: true,
    ctaText: "View Details",
  },
];

// Human-readable labels for each category slug, used on the catalogue page
const CATEGORY_LABELS = {
  "new": "What's New",
  "featured": "Featured This Week",
  "bundles": "Bundle Offers",
  "agriculture": "Agricultural Products",
  "coffee": "Coffee Products",
  "dairy": "Dairy Products",
  "seedlings": "Tree Seedlings",
  "merchandise": "DeKUT Merchandise",
  "wildlife": "Wildlife Tours",
  "conference": "Conference & Accommodation",
};

// Helper: find a single product by id (id comes from the URL as a string)
function getProductById(id) {
  return PRODUCTS.find(p => String(p.id) === String(id));
}

// Helper: render a 1-5 star rating as a string, e.g. 4.8 -> "★★★★★"
function renderStars(rating) {
  if (rating === null || rating === undefined) return "";
  const full = Math.round(rating);
  return "★".repeat(full) + "☆".repeat(5 - full);
}
